% -------------------------------------------------------------------
%  Generated by MATLAB on 30-Apr-2019 23:35:33
%  MATLAB version: 9.6.0.1072779 (R2019a)
% -------------------------------------------------------------------
                                                 

Init = struct;
Init.Chassis = struct;
Init.Chassis.aChassis = struct;
Init.Chassis.aChassis.Units = 'rad';
Init.Chassis.aChassis.Comments = '';
Init.Chassis.aChassis.Value = [0 0 0];
Init.Chassis.vChassis = struct;
Init.Chassis.vChassis.Units = 'm/s';
Init.Chassis.vChassis.Comments = '';
Init.Chassis.vChassis.Value = [0 0 0];
Init.Chassis.sChassis = struct;
Init.Chassis.sChassis.Units = 'm/s';
Init.Chassis.sChassis.Comments = '';
Init.Chassis.sChassis.Value = [0 0 0.12];
Init.Front = struct;
Init.Front.nWheel = struct;
Init.Front.nWheel.Units = 'rad/s';
Init.Front.nWheel.Comments = 'Values are [left right]';
Init.Front.nWheel.Value = [0 0 0.4225];
Init.Rear = struct;
Init.Rear.nWheel = struct;
Init.Rear.nWheel.Units = 'rad/s';
Init.Rear.nWheel.Comments = 'Values are [left right]';
Init.Rear.nWheel.Value = [0 0 0.4225];

